import type { Metadata } from 'next';
import { Chivo } from 'next/font/google';
import './globals.css';

import SessionWrapper from '@/components/SessionWrapper';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/toaster';

const chivo = Chivo({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SessionWrapper>
			<html lang="en">
				<body className={chivo.className}>
					<Navbar />
					<main className="flex justify-center items-center h-screen">
						{children}
					</main>
					<Toaster />
				</body>
			</html>
		</SessionWrapper>
	);
}
