import type { Metadata } from 'next';
import { Chivo } from 'next/font/google';
import './globals.css';

import SessionWrapper from '@/components/SessionWrapper';
import { Toaster } from '@/components/ui/toaster';
import { ThemeProvider } from '@/components/theme/theme-provider';
import { HomeNav } from '@/components/HomeNav';

const chivo = Chivo({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootlayoutProps {
	readonly children: React.ReactNode;
}

export default function RootLayout({ children }: RootlayoutProps) {
	return (
		<SessionWrapper>
			<html lang="en">
				<body className={chivo.className}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<main>{children}</main>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</SessionWrapper>
	);
}
